import { Inter } from 'next/font/google'
import './globals.css'
import { ChakraProvider } from '@chakra-ui/react'
import { Providers } from './redux/provider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'County local staffing',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
      <link
    href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap"
    rel="stylesheet"
  />
      </head> */}
      <body className={inter.className}>
        <Providers>
        <ChakraProvider>
        {children}
        </ChakraProvider>
        </Providers>
        </body>
    </html>
  )
}
